import { collection, doc, setDoc, serverTimestamp, db, handleFirestoreError, OperationType } from "../firebase";

export type Tradesperson = typeof INITIAL_MOCK_TRADERS[number];

export const INITIAL_MOCK_TRADERS = [
  {
    uid: "seed-promoted-plumber",
    email: "marcus.vance@eliteplumbing.co.uk",
    name: "Marcus Vance",
    businessName: "Elite Pro Plumbing & Heating 24/7",
    firstName: "Marcus",
    lastName: "Vance",
    role: "tradesperson",
    trades: ["Plumbing", "Gas & Heating", "Bathroom Fitting"],
    services: ["Boiler Installation", "Emergency Leak Repair", "Gas Safety Certification", "Full Bathroom Refurbishment"],
    tierId: "Gold",
    subscriptionType: "business",
    subscriptionTier: "gold",
    subscriptionStatus: "active",
    verificationStatus: "verified",
    postcode: "SW1A 1AA",
    bio: "Gas Safe Registered Master Plumber & Heating Specialist. 15+ years serving Central London. 24/7 emergency response guaranteed within 45 mins.",
    rating: 4.95,
    totalReviews: 184,
    totalRecommendations: 62,
    totalJobsDone: 320,
    completedJobsRevenue: 48000,
    trustScore: 99,
    responseRate: 99,
    isAcceptingRequests: true,
    isAvailableForEmergency: true,
    createdAt: new Date().toISOString(),
    avatarUrl: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&auto=format&fit=crop&q=80",
    searchFeedBadges: ["verified", "fast_reply", "top_rated", "guarantee"],
    miniProfileSettings: { callOutFee: 45, hourlyRate: 65, extraInfo: "24/7 Emergency Gas Safe Engineer. Free phone estimates & upfront transparent pricing." },
    recommendedCategories: ["Plumbing", "Gas & Heating"],
    videoVerificationStatus: "approved",
    stripeConnected: true,
    verificationDocs: [
      {
        type: "Public Liability Insurance",
        status: "approved",
        expiryDate: "2027-11-15",
        policyNumber: "AXA-PL-992014",
        fileName: "Marcus_Vance_Public_Liability_2M.pdf",
        fileUrl: "https://images.unsplash.com/photo-1450133064473-71024230f91b?w=800&auto=format&fit=crop&q=80",
        autoCheck: { message: "Matched active £2M Public Liability cover on AXA Insurance API.", status: "passed", provider: "AXA UK Insurance API" }
      },
      {
        type: "Gas Safe Register ID & WaterSafe",
        status: "approved",
        expiryDate: "2028-04-30",
        regNumber: "GS-5839201-UK",
        fileName: "Gas_Safe_Register_Card_Marcus_Vance.jpg",
        fileUrl: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&auto=format&fit=crop&q=80",
        autoCheck: { message: "Verified active Gas Safe Engineer #5839201 in Gas Safe Register API.", status: "passed", provider: "Gas Safe Register API" }
      },
      {
        type: "Identity Verification (Passport/Driving License)",
        status: "approved",
        expiryDate: "2031-08-20",
        idNumber: "VANCE880193MV99",
        fileName: "UK_Driving_License_Marcus_Vance.jpg",
        fileUrl: "https://images.unsplash.com/photo-1544717305-2782549b5136?w=800&auto=format&fit=crop&q=80",
        autoCheck: { message: "Biometric photo ID matched against DVLA GB driver database.", status: "passed", provider: "DVLA Driver Verification API" }
      }
    ],
  },
  {
    uid: "seed-promoted-electrician",
    email: "sarah.jenkins@voltmaster.co.uk",
    name: "Sarah Jenkins",
    businessName: "VoltMaster Electrical & Smart Home",
    firstName: "Sarah",
    lastName: "Jenkins",
    role: "tradesperson",
    trades: ["Electrical", "Smart Home & Automation", "Security Systems"],
    services: ["Full Consumer Unit Upgrade", "EV Charger Fitting", "CCTV & Alarm Systems", "EICR Safety Inspection"],
    tierId: "Pro",
    subscriptionType: "pro",
    subscriptionTier: "pro",
    subscriptionStatus: "active",
    verificationStatus: "verified",
    postcode: "E1 6SJ",
    bio: "NICEIC Approved Electrical Contractor. Smart home integrations specialist (Loxone, Hue, Ring, Nest). Commercial and domestic compliance certified.",
    rating: 4.90,
    totalReviews: 142,
    totalRecommendations: 48,
    totalJobsDone: 210,
    completedJobsRevenue: 31500,
    trustScore: 98,
    responseRate: 97,
    isAcceptingRequests: true,
    isAvailableForEmergency: false,
    createdAt: new Date().toISOString(),
    avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80",
    searchFeedBadges: ["verified", "fast_reply", "top_rated"],
    miniProfileSettings: { callOutFee: 50, hourlyRate: 70, extraInfo: "NICEIC Certified with 10-year workmanship warranty on consumer unit upgrades." },
    recommendedCategories: ["Electrical", "Smart Home & Automation"],
  },
  {
    uid: "seed-promoted-baker",
    email: "chloe.dupont@artisancakes.co.uk",
    name: "Chloe Dupont",
    businessName: "Artisan Sweet & Savoury Creations",
    firstName: "Chloe",
    lastName: "Dupont",
    role: "tradesperson",
    trades: ["Cake Maker & Baker", "Catering & Private Chef"],
    services: ["Bespoke Wedding Cakes", "Corporate Buffet Catering", "Artisan Cupcake Towers", "Private Dinner Chef"],
    tierId: "Platinum",
    subscriptionType: "business",
    subscriptionTier: "platinum",
    subscriptionStatus: "active",
    verificationStatus: "verified",
    postcode: "W1D 3QU",
    bio: "Award-winning French Pastry Chef & Caterer. 5-Star Hygiene Rated by FSA. Specialized in luxury wedding cakes, corporate events, and bespoke dietary menus.",
    rating: 5.0,
    totalReviews: 96,
    totalRecommendations: 39,
    totalJobsDone: 175,
    completedJobsRevenue: 26250,
    trustScore: 100,
    responseRate: 100,
    isAcceptingRequests: true,
    isAvailableForEmergency: false,
    createdAt: new Date().toISOString(),
    avatarUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&auto=format&fit=crop&q=80",
    searchFeedBadges: ["verified", "top_rated", "guarantee"],
    miniProfileSettings: { callOutFee: 0, hourlyRate: 50, extraInfo: "5-Star FSA Hygiene Rating. Free tasting consultations for weddings and large events." },
    recommendedCategories: ["Cake Maker & Baker", "Catering & Private Chef"],
  },
  {
    uid: "seed-promoted-cleaner",
    email: "david.oconnor@pristineclean.co.uk",
    name: "David O'Connor",
    businessName: "Pristine Shine Eco Cleaners",
    firstName: "David",
    lastName: "O'Connor",
    role: "tradesperson",
    trades: ["Domestic & Commercial Cleaning", "Carpet & Upholstery Cleaning"],
    services: ["End of Tenancy Deep Clean", "Commercial Office Maintenance", "Eco Carpet Steam Clean", "Window Cleaning"],
    tierId: "Pro",
    subscriptionType: "pro",
    subscriptionTier: "pro",
    subscriptionStatus: "active",
    verificationStatus: "verified",
    postcode: "NW1 8AL",
    bio: "Eco-friendly commercial and domestic cleaning team. COSHH compliant, fully insured with £5M liability cover. Guaranteed deposit back for end of tenancy.",
    rating: 4.88,
    totalReviews: 115,
    totalRecommendations: 31,
    totalJobsDone: 290,
    completedJobsRevenue: 20300,
    trustScore: 97,
    responseRate: 98,
    isAcceptingRequests: true,
    isAvailableForEmergency: true,
    createdAt: new Date().toISOString(),
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80",
    searchFeedBadges: ["verified", "fast_reply", "guarantee"],
    miniProfileSettings: { callOutFee: 25, hourlyRate: 30, extraInfo: "Deposit-back guarantee for all end-of-tenancy deep cleans." },
    recommendedCategories: ["Domestic & Commercial Cleaning"],
  },
  {
    uid: "seed-promoted-builder",
    email: "liam.gallagher@apexbuilders.co.uk",
    name: "Liam Gallagher",
    businessName: "Apex Master Builders & Roofing",
    firstName: "Liam",
    lastName: "Gallagher",
    role: "tradesperson",
    trades: ["Builder", "Carpentry & Joinery", "Roofing Services"],
    services: ["House Extension", "Loft Conversion", "Slate Roofing Repair", "Custom Timber Decking"],
    tierId: "Gold",
    subscriptionType: "business",
    subscriptionTier: "gold",
    subscriptionStatus: "active",
    verificationStatus: "verified",
    postcode: "SE1 9SG",
    bio: "Federation of Master Builders member. 20 years constructing high-end extensions, loft conversions, and roof restorations in South East England.",
    rating: 4.92,
    totalReviews: 158,
    totalRecommendations: 54,
    totalJobsDone: 205,
    completedJobsRevenue: 123000,
    trustScore: 99,
    responseRate: 96,
    isAcceptingRequests: true,
    isAvailableForEmergency: true,
    createdAt: new Date().toISOString(),
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80",
    searchFeedBadges: ["verified", "top_rated", "guarantee"],
    miniProfileSettings: { callOutFee: 60, hourlyRate: 85, extraInfo: "Master Builder certified. Full structural warranty on extensions & conversions." },
    recommendedCategories: ["Builder", "Roofing Services", "Carpentry & Joinery"],
  },
  {
    uid: "seed-promoted-locksmith",
    email: "james.miller@rapidlocksmiths.co.uk",
    name: "James Miller",
    businessName: "24/7 Rapid Master Locksmiths & Security",
    firstName: "James",
    lastName: "Miller",
    role: "tradesperson",
    trades: ["Locksmith", "Security Systems"],
    services: ["Emergency Non-Destructive Door Opening", "British Standard Ultion Lock Installation", "Commercial Master Key Systems", "Smart Keyless Lock Setup"],
    tierId: "Gold",
    subscriptionType: "business",
    subscriptionTier: "gold",
    subscriptionStatus: "active",
    verificationStatus: "verified",
    postcode: "W1K 4QG",
    bio: "MLA Approved Master Locksmith & Safe Engineer. 20-minute rapid mobile response across Greater London. Specialised in high-security anti-snap locks.",
    rating: 4.98,
    totalReviews: 212,
    totalRecommendations: 78,
    totalJobsDone: 440,
    completedJobsRevenue: 52800,
    trustScore: 100,
    responseRate: 100,
    isAcceptingRequests: true,
    isAvailableForEmergency: true,
    createdAt: new Date().toISOString(),
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80",
    searchFeedBadges: ["verified", "fast_reply", "top_rated", "guarantee"],
    miniProfileSettings: { callOutFee: 40, hourlyRate: 60, extraInfo: "20-minute emergency lockout arrival. British Standard 3-star diamond anti-snap cylinders." },
    recommendedCategories: ["Locksmith", "Security Systems"],
  },
  {
    uid: "seed-promoted-decorator",
    email: "elena.rostova@heritagedecor.co.uk",
    name: "Elena Rostova",
    businessName: "Heritage Luxe Painting & Decorating",
    firstName: "Elena",
    lastName: "Rostova",
    role: "tradesperson",
    trades: ["Painting & Decorating", "Plastering"],
    services: ["Interior Heritage Emulsion & Gloss", "Farrow & Ball Colour Consultation", "Exterior Masonry & Woodwork", "Dustless Airless Spray Plastering"],
    tierId: "Pro",
    subscriptionType: "pro",
    subscriptionTier: "pro",
    subscriptionStatus: "active",
    verificationStatus: "verified",
    postcode: "SW3 4AA",
    bio: "City & Guilds Master Painter & Decorator. Specialist in luxury residential finishes, period property preservation, and high-end wallpaper hanging.",
    rating: 4.96,
    totalReviews: 134,
    totalRecommendations: 51,
    totalJobsDone: 180,
    completedJobsRevenue: 43200,
    trustScore: 99,
    responseRate: 98,
    isAcceptingRequests: true,
    isAvailableForEmergency: false,
    createdAt: new Date().toISOString(),
    avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&auto=format&fit=crop&q=80",
    searchFeedBadges: ["verified", "top_rated", "guarantee"],
    miniProfileSettings: { callOutFee: 0, hourlyRate: 45, extraInfo: "Farrow & Ball approved applicator. Free bespoke color swatches & written estimates." },
    recommendedCategories: ["Painting & Decorating"],
  },
  {
    uid: "seed-promoted-tailor",
    email: "amira.hassan@savilestitch.co.uk",
    name: "Amira Hassan",
    businessName: "Savile & Stitch Master Tailoring & Alterations",
    firstName: "Amira",
    lastName: "Hassan",
    role: "tradesperson",
    trades: ["Tailoring, Alterations & Laundry Services", "Bespoke Tailoring", "Garment Alterations"],
    services: ["Suit & Jacket Resizing", "Wedding Dress & Bridal Alterations", "Trousers Hemming & Tapering", "Professional Ironing & Laundry Service", "Zip & Lining Replacement"],
    tierId: "Gold",
    subscriptionType: "business",
    subscriptionTier: "gold",
    subscriptionStatus: "active",
    verificationStatus: "verified",
    postcode: "W1S 2JR",
    bio: "Savile Row trained master tailor & seamstress with 18+ years experience in bespoke suiting, delicate bridal alterations, leather repairs, and professional garment care.",
    rating: 4.97,
    totalReviews: 128,
    totalRecommendations: 64,
    totalJobsDone: 310,
    completedJobsRevenue: 37200,
    trustScore: 99,
    responseRate: 99,
    isAcceptingRequests: true,
    isAvailableForEmergency: true,
    createdAt: new Date().toISOString(),
    avatarUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&auto=format&fit=crop&q=80",
    searchFeedBadges: ["verified", "top_rated", "fast_reply", "guarantee"],
    miniProfileSettings: { callOutFee: 0, hourlyRate: 40, extraInfo: "Express 24-48h turnaround available. Free fittings & consultations across Central London." },
    recommendedCategories: ["Tailoring, Alterations & Laundry Services"],
  }
];

export const INITIAL_MOCK_FLASH_DEALS = [
  {
    id: "deal-marcus-boiler",
    traderId: "seed-promoted-plumber",
    traderName: "Marcus Vance",
    traderAvatarUrl: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&auto=format&fit=crop&q=80",
    service: "Annual Boiler Servicing & Safety Check",
    category: "Plumbing & Heating",
    discountPercentage: 25,
    originalPrice: 120,
    discountedPrice: 90,
    dayOfWeek: "Tuesday",
    description: "Get 25% off annual gas boiler servicing and CP12 certificate when booked for off-peak Tuesdays.",
    status: "active",
    maxClaims: 5,
    claimedCount: 2,
    createdAt: new Date().toISOString(),
    city: "London",
    postcode: "SW1A 1AA"
  },
  {
    id: "deal-sarah-eicr",
    traderId: "seed-promoted-electrician",
    traderName: "Sarah Jenkins",
    traderAvatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80",
    service: "EICR Safety Inspection & EV Charger",
    category: "Electrical",
    discountPercentage: 20,
    originalPrice: 250,
    discountedPrice: 200,
    dayOfWeek: "Wednesday",
    description: "Special Wednesday off-peak rate for domestic landlord EICRs and home EV charge point installations.",
    status: "active",
    maxClaims: 3,
    claimedCount: 1,
    createdAt: new Date().toISOString(),
    city: "London",
    postcode: "E1 6SJ"
  },
  {
    id: "deal-david-carpet",
    traderId: "seed-promoted-cleaner",
    traderName: "David O'Connor",
    traderAvatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80",
    service: "Eco Carpet Steam Clean & Wheelie Bin Wash",
    category: "Specialist Cleaning",
    discountPercentage: 30,
    originalPrice: 100,
    discountedPrice: 70,
    dayOfWeek: "Thursday",
    description: "30% off deep carpet steam extraction and high-pressure wheelie bin sanitising every Thursday.",
    status: "active",
    maxClaims: 5,
    claimedCount: 3,
    createdAt: new Date().toISOString(),
    city: "London",
    postcode: "NW1 8AL"
  },
  {
    id: "deal-chloe-catering",
    traderId: "seed-promoted-baker",
    traderName: "Chloe Dupont",
    traderAvatarUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&auto=format&fit=crop&q=80",
    service: "Corporate Buffet & Wedding Cake Tasting Box",
    category: "Catering & Private Chef",
    discountPercentage: 15,
    originalPrice: 180,
    discountedPrice: 153,
    dayOfWeek: "Monday",
    description: "Kick off your week with 15% off artisanal corporate catering platters and wedding cake sample boxes.",
    status: "active",
    maxClaims: 4,
    claimedCount: 4,
    createdAt: new Date().toISOString(),
    city: "London",
    postcode: "W1D 3QU"
  },
  {
    id: "deal-liam-roof",
    traderId: "seed-promoted-builder",
    traderName: "Liam Gallagher",
    traderAvatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80",
    service: "Drone Roof Survey & Full Gutter Clearance",
    category: "Roofing & Guttering",
    discountPercentage: 20,
    originalPrice: 200,
    discountedPrice: 160,
    dayOfWeek: "Friday",
    description: "20% off high-reach drone roof condition survey and full gutter clearance every Friday.",
    status: "active",
    maxClaims: null,
    claimedCount: 1,
    createdAt: new Date().toISOString(),
    city: "London",
    postcode: "SE1 9SG"
  }
];

export const seedMockTraders = async () => {
  const mockTraders = INITIAL_MOCK_TRADERS.map(t => ({
    ...t,
    createdAt: serverTimestamp()
  }));

  const mockAds = [
    {
      id: "ad-promoted-plumber",
      advertiserUid: "seed-promoted-plumber",
      title: "Elite Pro Plumbing 24/7",
      tagline: "Gas Safe Master Plumber. 24/7 emergency burst pipe, boiler & leak repairs in 45 mins.",
      description: "Gas Safe Master Plumber. 24/7 emergency burst pipe, boiler & leak repairs in 45 mins.",
      url: "/profile/seed-promoted-plumber",
      perkText: "⚡ 45-Min Emergency Arrival",
      placement: "both",
      approvalStatus: "approved",
      isActive: true,
      prepaidBalance: 250.00,
      targetCategories: ["Plumbing", "Gas & Heating", "all"],
      promotionRadius: "nationwide",
      costPerDisplay: 1.00,
      clicks: 24,
      searchFeedClicks: 18,
      createdAt: new Date().toISOString()
    },
    {
      id: "ad-promoted-electrician",
      advertiserUid: "seed-promoted-electrician",
      title: "VoltMaster Electrical & EV Charging",
      tagline: "NICEIC Approved Contractors. EV charger installations & 18th edition consumer unit upgrades.",
      description: "NICEIC Approved Contractors. EV charger installations & 18th edition consumer unit upgrades.",
      url: "/profile/seed-promoted-electrician",
      perkText: "⚡ NICEIC Approved & EV Specialist",
      placement: "both",
      approvalStatus: "approved",
      isActive: true,
      prepaidBalance: 180.00,
      targetCategories: ["Electrical", "Smart Home & Automation", "all"],
      promotionRadius: "nationwide",
      costPerDisplay: 1.20,
      clicks: 19,
      searchFeedClicks: 14,
      createdAt: new Date().toISOString()
    },
    {
      id: "ad-promoted-builder",
      advertiserUid: "seed-promoted-builder",
      title: "Apex Master Builders & Roofing",
      tagline: "Master Builder certified extensions, loft conversions, structural steel & roof restorations.",
      description: "Master Builder certified extensions, loft conversions, structural steel & roof restorations.",
      url: "/profile/seed-promoted-builder",
      perkText: "⭐ Federation of Master Builders",
      placement: "both",
      approvalStatus: "approved",
      isActive: true,
      prepaidBalance: 400.00,
      targetCategories: ["Builder", "Roofing Services", "Carpentry & Joinery", "all"],
      promotionRadius: "nationwide",
      costPerDisplay: 1.50,
      clicks: 42,
      searchFeedClicks: 30,
      createdAt: new Date().toISOString()
    },
    {
      id: "ad-promoted-locksmith",
      advertiserUid: "seed-promoted-locksmith",
      title: "24/7 Rapid Master Locksmiths",
      tagline: "20-minute emergency lockout assistance, Ultion anti-snap cylinders & high security upgrades.",
      description: "20-minute emergency lockout assistance, Ultion anti-snap cylinders & high security upgrades.",
      url: "/profile/seed-promoted-locksmith",
      perkText: "⚡ 20-Min Mobile Lockout Arrival",
      placement: "both",
      approvalStatus: "approved",
      isActive: true,
      prepaidBalance: 220.00,
      targetCategories: ["Locksmith", "Security Systems", "all"],
      promotionRadius: "nationwide",
      costPerDisplay: 1.10,
      clicks: 28,
      searchFeedClicks: 21,
      createdAt: new Date().toISOString()
    },
    {
      id: "ad-promoted-decorator",
      advertiserUid: "seed-promoted-decorator",
      title: "Heritage Luxe Painting & Decorating",
      tagline: "City & Guilds master painters. Heritage preservation, Farrow & Ball paint and airless spray finishes.",
      description: "City & Guilds master painters. Heritage preservation, Farrow & Ball paint and airless spray finishes.",
      url: "/profile/seed-promoted-decorator",
      perkText: "✨ Farrow & Ball Approved",
      placement: "both",
      approvalStatus: "approved",
      isActive: true,
      prepaidBalance: 190.00,
      targetCategories: ["Painting & Decorating", "Plastering", "all"],
      promotionRadius: "nationwide",
      costPerDisplay: 0.95,
      clicks: 16,
      searchFeedClicks: 12,
      createdAt: new Date().toISOString()
    },
    {
      id: "ad-promoted-cleaner",
      advertiserUid: "seed-promoted-cleaner",
      title: "Pristine Shine Eco Deep Cleaning",
      tagline: "100% deposit-back guaranteed end of tenancy cleaning, eco carpet steam & commercial sanitation.",
      description: "100% deposit-back guaranteed end of tenancy cleaning, eco carpet steam & commercial sanitation.",
      url: "/profile/seed-promoted-cleaner",
      perkText: "🛡️ Deposit-Back Guarantee",
      placement: "both",
      approvalStatus: "approved",
      isActive: true,
      prepaidBalance: 150.00,
      targetCategories: ["Domestic & Commercial Cleaning", "all"],
      promotionRadius: "nationwide",
      costPerDisplay: 0.90,
      clicks: 15,
      searchFeedClicks: 11,
      createdAt: new Date().toISOString()
    },
    {
      id: "ad-promoted-baker",
      advertiserUid: "seed-promoted-baker",
      title: "Artisan Wedding Cakes & Event Catering",
      tagline: "5-Star hygiene rated luxury wedding cakes, corporate event grazing tables & private chef dining.",
      description: "5-Star hygiene rated luxury wedding cakes, corporate event grazing tables & private chef dining.",
      url: "/profile/seed-promoted-baker",
      perkText: "🍰 5-Star FSA Hygiene Rated",
      placement: "both",
      approvalStatus: "approved",
      isActive: true,
      prepaidBalance: 300.00,
      targetCategories: ["Cake Maker & Baker", "Catering & Private Chef", "all"],
      promotionRadius: "nationwide",
      costPerDisplay: 1.50,
      clicks: 31,
      searchFeedClicks: 25,
      createdAt: new Date().toISOString()
    }
  ];

  try {
    for (const trader of mockTraders) {
      await setDoc(doc(db, "users", trader.uid), trader, { merge: true });
    }
    for (const ad of mockAds) {
      await setDoc(doc(db, "advertisements", ad.id), ad, { merge: true });
    }
    for (const deal of INITIAL_MOCK_FLASH_DEALS) {
      await setDoc(doc(db, "flash_deals", deal.id), deal, { merge: true });
    }
    console.log("5 Promoted & Paid Subscriber Profiles & Flash Deals created in Plumbing, Electrical, Baking, Cleaning, and Building!");
  } catch (error) {
    console.error("Error seeding mock traders & ads:", error);
    handleFirestoreError(error, OperationType.WRITE, "users");
  }
};
