import { collection, doc, setDoc, serverTimestamp, db, handleFirestoreError, OperationType } from "../firebase";

export const seedMockTraders = async () => {
  const mockTraders = [
    {
      uid: "seed-promoted-plumber",
      email: "marcus.vance@eliteplumbing.co.uk",
      name: "Marcus Vance",
      businessName: "Elite Pro Plumbing & Heating 24/7",
      firstName: "Marcus",
      lastName: "Vance",
      role: "tradesperson",
      trades: ["Plumbing", "Gas & Heating", "Bathroom Fitting"],
      services: ["Boiler Installation", "Emergency Leak Repair", "Gas Safety Certification", "Full Bathroom Refurbishment"],
      tierId: "Gold",
      subscriptionType: "business",
      subscriptionTier: "gold",
      subscriptionStatus: "active",
      verificationStatus: "verified",
      postcode: "SW1A 1AA",
      bio: "Gas Safe Registered Master Plumber & Heating Specialist. 15+ years serving Central London. 24/7 emergency response guaranteed within 45 mins.",
      rating: 4.95,
      totalReviews: 184,
      totalRecommendations: 62,
      totalJobsDone: 320,
      completedJobsRevenue: 48000,
      trustScore: 99,
      responseRate: 99,
      isAcceptingRequests: true,
      isAvailableForEmergency: true,
      createdAt: serverTimestamp(),
      avatarUrl: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&auto=format&fit=crop&q=80",
      searchFeedBadges: ["verified", "fast_reply", "top_rated", "guarantee"],
      miniProfileSettings: { callOutFee: 45, hourlyRate: 65, extraInfo: "24/7 Emergency Gas Safe Engineer. Free phone estimates & upfront transparent pricing." },
      recommendedCategories: ["Plumbing", "Gas & Heating"],
    },
    {
      uid: "seed-promoted-electrician",
      email: "sarah.jenkins@voltmaster.co.uk",
      name: "Sarah Jenkins",
      businessName: "VoltMaster Electrical & Smart Home",
      firstName: "Sarah",
      lastName: "Jenkins",
      role: "tradesperson",
      trades: ["Electrical", "Smart Home & Automation", "Security Systems"],
      services: ["Full Consumer Unit Upgrade", "EV Charger Fitting", "CCTV & Alarm Systems", "EICR Safety Inspection"],
      tierId: "Pro",
      subscriptionType: "pro",
      subscriptionTier: "pro",
      subscriptionStatus: "active",
      verificationStatus: "verified",
      postcode: "E1 6SJ",
      bio: "NICEIC Approved Electrical Contractor. Smart home integrations specialist (Loxone, Hue, Ring, Nest). Commercial and domestic compliance certified.",
      rating: 4.90,
      totalReviews: 142,
      totalRecommendations: 48,
      totalJobsDone: 210,
      completedJobsRevenue: 31500,
      trustScore: 98,
      responseRate: 97,
      isAcceptingRequests: true,
      isAvailableForEmergency: false,
      createdAt: serverTimestamp(),
      avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80",
      searchFeedBadges: ["verified", "fast_reply", "top_rated"],
      miniProfileSettings: { callOutFee: 50, hourlyRate: 70, extraInfo: "NICEIC Certified with 10-year workmanship warranty on consumer unit upgrades." },
      recommendedCategories: ["Electrical", "Smart Home & Automation"],
    },
    {
      uid: "seed-promoted-baker",
      email: "chloe.dupont@artisancakes.co.uk",
      name: "Chloe Dupont",
      businessName: "Artisan Sweet & Savoury Creations",
      firstName: "Chloe",
      lastName: "Dupont",
      role: "tradesperson",
      trades: ["Cake Maker & Baker", "Catering & Private Chef"],
      services: ["Bespoke Wedding Cakes", "Corporate Buffet Catering", "Artisan Cupcake Towers", "Private Dinner Chef"],
      tierId: "Platinum",
      subscriptionType: "business",
      subscriptionTier: "platinum",
      subscriptionStatus: "active",
      verificationStatus: "verified",
      postcode: "W1D 3QU",
      bio: "Award-winning French Pastry Chef & Caterer. 5-Star Hygiene Rated by FSA. Specialized in luxury wedding cakes, corporate events, and bespoke dietary menus.",
      rating: 5.0,
      totalReviews: 96,
      totalRecommendations: 39,
      totalJobsDone: 175,
      completedJobsRevenue: 26250,
      trustScore: 100,
      responseRate: 100,
      isAcceptingRequests: true,
      isAvailableForEmergency: false,
      createdAt: serverTimestamp(),
      avatarUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&auto=format&fit=crop&q=80",
      searchFeedBadges: ["verified", "top_rated", "guarantee"],
      miniProfileSettings: { callOutFee: 0, hourlyRate: 50, extraInfo: "5-Star FSA Hygiene Rating. Free tasting consultations for weddings and large events." },
      recommendedCategories: ["Cake Maker & Baker", "Catering & Private Chef"],
    },
    {
      uid: "seed-promoted-cleaner",
      email: "david.oconnor@pristineclean.co.uk",
      name: "David O'Connor",
      businessName: "Pristine Shine Eco Cleaners",
      firstName: "David",
      lastName: "O'Connor",
      role: "tradesperson",
      trades: ["Domestic & Commercial Cleaning", "Carpet & Upholstery Cleaning"],
      services: ["End of Tenancy Deep Clean", "Commercial Office Maintenance", "Eco Carpet Steam Clean", "Window Cleaning"],
      tierId: "Pro",
      subscriptionType: "pro",
      subscriptionTier: "pro",
      subscriptionStatus: "active",
      verificationStatus: "verified",
      postcode: "NW1 8AL",
      bio: "Eco-friendly commercial and domestic cleaning team. COSHH compliant, fully insured with £5M liability cover. Guaranteed deposit back for end of tenancy.",
      rating: 4.88,
      totalReviews: 115,
      totalRecommendations: 31,
      totalJobsDone: 290,
      completedJobsRevenue: 20300,
      trustScore: 97,
      responseRate: 98,
      isAcceptingRequests: true,
      isAvailableForEmergency: true,
      createdAt: serverTimestamp(),
      avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80",
      searchFeedBadges: ["verified", "fast_reply", "guarantee"],
      miniProfileSettings: { callOutFee: 25, hourlyRate: 30, extraInfo: "Deposit-back guarantee for all end-of-tenancy deep cleans." },
      recommendedCategories: ["Domestic & Commercial Cleaning"],
    },
    {
      uid: "seed-promoted-builder",
      email: "liam.gallagher@apexbuilders.co.uk",
      name: "Liam Gallagher",
      businessName: "Apex Master Builders & Roofing",
      firstName: "Liam",
      lastName: "Gallagher",
      role: "tradesperson",
      trades: ["Builder", "Carpentry & Joinery", "Roofing Services"],
      services: ["House Extension", "Loft Conversion", "Slate Roofing Repair", "Custom Timber Decking"],
      tierId: "Gold",
      subscriptionType: "business",
      subscriptionTier: "gold",
      subscriptionStatus: "active",
      verificationStatus: "verified",
      postcode: "SE1 9SG",
      bio: "Federation of Master Builders member. 20 years constructing high-end extensions, loft conversions, and roof restorations in South East England.",
      rating: 4.92,
      totalReviews: 158,
      totalRecommendations: 54,
      totalJobsDone: 205,
      completedJobsRevenue: 123000,
      trustScore: 99,
      responseRate: 96,
      isAcceptingRequests: true,
      isAvailableForEmergency: true,
      createdAt: serverTimestamp(),
      avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80",
      searchFeedBadges: ["verified", "top_rated", "guarantee"],
      miniProfileSettings: { callOutFee: 60, hourlyRate: 85, extraInfo: "Master Builder certified. Full structural warranty on extensions & conversions." },
      recommendedCategories: ["Builder", "Roofing Services", "Carpentry & Joinery"],
    }
  ];

  const mockAds = [
    {
      id: "ad-promoted-plumber",
      advertiserUid: "seed-promoted-plumber",
      title: "Elite Pro Plumbing 24/7",
      tagline: "Top-rated emergency plumber in London. Fast 45 min arrival!",
      placement: "both",
      approvalStatus: "approved",
      isActive: true,
      prepaidBalance: 250.00,
      targetCategories: ["Plumbing", "Gas & Heating", "all"],
      promotionRadius: "nationwide",
      costPerDisplay: 1.00,
      clicks: 24,
      searchFeedClicks: 18,
      createdAt: new Date().toISOString()
    },
    {
      id: "ad-promoted-electrician",
      advertiserUid: "seed-promoted-electrician",
      title: "VoltMaster Electrical Services",
      tagline: "NICEIC Approved Electricians & EV Charging Installations.",
      placement: "search_feed",
      approvalStatus: "approved",
      isActive: true,
      prepaidBalance: 180.00,
      targetCategories: ["Electrical", "Smart Home & Automation", "all"],
      promotionRadius: "nationwide",
      costPerDisplay: 1.20,
      clicks: 19,
      searchFeedClicks: 14,
      createdAt: new Date().toISOString()
    },
    {
      id: "ad-promoted-baker",
      advertiserUid: "seed-promoted-baker",
      title: "Artisan Wedding & Celebration Cakes",
      tagline: "Award-winning luxury cakes & event catering across London.",
      placement: "search_feed",
      approvalStatus: "approved",
      isActive: true,
      prepaidBalance: 300.00,
      targetCategories: ["Cake Maker & Baker", "Catering & Private Chef", "all"],
      promotionRadius: "nationwide",
      costPerDisplay: 1.50,
      clicks: 31,
      searchFeedClicks: 25,
      createdAt: new Date().toISOString()
    },
    {
      id: "ad-promoted-cleaner",
      advertiserUid: "seed-promoted-cleaner",
      title: "Pristine Shine Eco Cleaning",
      tagline: "Guaranteed Deposit-Back End of Tenancy & Office Cleaning.",
      placement: "search_feed",
      approvalStatus: "approved",
      isActive: true,
      prepaidBalance: 150.00,
      targetCategories: ["Domestic & Commercial Cleaning", "all"],
      promotionRadius: "nationwide",
      costPerDisplay: 0.90,
      clicks: 15,
      searchFeedClicks: 11,
      createdAt: new Date().toISOString()
    },
    {
      id: "ad-promoted-builder",
      advertiserUid: "seed-promoted-builder",
      title: "Apex Master Builders & Roofing",
      tagline: "Master Builder extensions, loft conversions & roof restoration.",
      placement: "both",
      approvalStatus: "approved",
      isActive: true,
      prepaidBalance: 400.00,
      targetCategories: ["Builder", "Roofing Services", "Carpentry & Joinery", "all"],
      promotionRadius: "nationwide",
      costPerDisplay: 1.50,
      clicks: 42,
      searchFeedClicks: 30,
      createdAt: new Date().toISOString()
    }
  ];

  try {
    for (const trader of mockTraders) {
      await setDoc(doc(db, "users", trader.uid), trader, { merge: true });
    }
    for (const ad of mockAds) {
      await setDoc(doc(db, "advertisements", ad.id), ad, { merge: true });
    }
    console.log("5 Promoted & Paid Subscriber Profiles created in Plumbing, Electrical, Baking, Cleaning, and Building!");
  } catch (error) {
    console.error("Error seeding mock traders & ads:", error);
    handleFirestoreError(error, OperationType.WRITE, "users");
  }
};
